---
version: '2'
services:
  # ZooKeeper is a centralized service for maintaining configuration information, naming, providing distributed  
  # synchronization, and providiing group services.  ZooKeeper is managing the Kafka cluster in this instance.
  # tick_time is used for synchronization across distributed systems.
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
    expose:
      - "2181"
      - "2888"
      - "32181"
      - "3888"
    extra_hosts:
      - "moby:127.0.0.1"
      
  # Code block used to setup Kafka.  
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    expose:
      - "9092"
      - "29092"
    extra_hosts:
      - "moby:127.0.0.1"

  # The cloudera service houses the hadoop file system.
  # The hive thrift server is used to access tables and infer schema.
  # Presto looks to the hive thrift store to get the relevant meta information from the meta store.
  # Hive can be referred to as the phone book to get tables.
  cloudera:
    image: midsw205/hadoop:0.0.2
    hostname: cloudera
    expose:
      - "8020" # nn
      - "8888" # hue
      - "9083" # hive thrift
      - "10000" # hive jdbc
      - "50070" # nn http
    ports:
      - "8888:8888"
    extra_hosts:
      - "moby:127.0.0.1"
      
  # The spark service is used to execute streaming jobs using spark.  
  # Port 8890 is opened for communication. I can open a spark notebook if needed.
  # Note the depends on: cloudera line.
  # Hive thrift store is a metastore used with presto.
  spark:
    image: midsw205/spark-python:0.0.6
    stdin_open: true
    tty: true
    volumes:
      - ~/w205:/w205
    expose:
      - "8888"
      - "8890"
    ports:
      - "8889:8888" # 8888 conflicts with hue
      - "8890:8890"
    depends_on:
      - cloudera
    environment:
      HADOOP_NAMENODE: cloudera
      HIVE_THRIFTSERVER: cloudera:9083
    extra_hosts:
      - "moby:127.0.0.1"
    command: bash
    
  # The presto service is used to query from the hadoop file system.
  # Moby is present for use on windows machines.
  # The hive thrift store has the same port as in the spark and cloudera service.
  presto:
    image: midsw205/presto:0.0.1
    hostname: presto
    volumes:
      - ~/w205:/w205
    expose:
      - "8080"
    environment:
      HIVE_THRIFTSERVER: cloudera:9083
    extra_hosts:
      - "moby:127.0.0.1"
      
  # The mids containers holds a lot of the tools we have at our disposal. 
  # We attach the mids container to use the tools that it contains.
  # Port 5000 is opened to communicate with the flask service.
  mids:
    image: midsw205/base:0.1.9
    stdin_open: true
    tty: true
    volumes:
      - ~/w205:/w205
    expose:
      - "5000"
    ports:
      - "5000:5000"
    extra_hosts:
      - "moby:127.0.0.1"

